services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
