app:
  environment: development
  log_level: info

server:
  host: 0.0.0.0
  port: 8080

database:
  mongodb:
    host: localhost
    port: 27017
    database: payment_db
    username: ""
    password: ""
    # Alternative: use full URI
    # uri: "mongodb://username:password@localhost:27017/payment_db"
