name: CI Pipeline

on:
  push:
    branches: [ backend, frontend ]
  pull_request:
    branches: [ backend, frontend ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'
        cache: true

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: transzure/payment:latest

    # Uncomment to enable Docker push to registry
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    #
    # - name: Push to Docker Hub
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: .
    #     push: true
    #     tags: transzure/payment:latest
